codecov:
  require_ci_to_pass: yes

coverage:
  range: 20..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:
        target: auto
        # don't allow new commits to decrease coverage
        threshold: 0.01%


    patch: false                 # measuring the coverage of new changes
