apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-config
  namespace: {{.Release.Namespace}}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
data:
  pipelineRunner: "{{ index .Values "image" }}"
