apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-runner
  namespace: {{ .Release.Namespace }}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.iamRole }}"