apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-down-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-down-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups: ["batch", "extensions"]
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups: ["apps"]
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-down-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-down-operator
subjects:
- kind: ServiceAccount
  name: scale-down-operator